language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; 
    then 
      brew tap homebrew/science;
      brew update > /dev/null 2>&1;
      brew install --quiet eigen;
      brew install --quiet nlopt;
      brew install --quiet tbb --c++11;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then 
      sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
      sudo apt-get install -qq gcc-4.4 g++-4.4 libstdc++6-4.4-dev;
      sudo apt-get install -qq libboost-dev;
      sudo apt-get install -qq libboost-test-dev;
      sudo apt-get install -qq libeigen3-dev;
      sudo apt-get install -qq libtbb-dev;
    fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then 
      export CC=gcc-4.4;
      export CXX=g++-4.4;
      cmake -DBUILD_TESTING=ON  .; 
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; 
    then 
      cmake -DBUILD_TESTING=ON  .; 
    fi

script:
  - make
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
